language: python
python:
- 3.6.3
sudo: required
install:
- pip install flask
script:
- python test.py
deploy:
  provider: heroku
  api_key:
    secure: fuCt83E2+s0iNgknxLZuiL6vjDoIaNaO8ubpd5aPpmXPhiBpaj/tjIl7IpUJX7yz4pNEK+Y36pLTlNXIB6SDut+dwpk55/GqrHdq4idH+0KSvH3cOHkCZw+aJWEEYeYTcnb9nZrPUAugk5r/jvqmIM6nVUL/eEVwcOzDZ0VzCrXvD/i6Yn25NjtjdwIDURV4DULFJIBW9oQp7xs7c7wgflzsOqQRk75E/PsCe0crvq/a39viGHAXHmMujaIZB1Uw4rsyW7Bhmitqka2JjUYlyzlSgEQVuqpuYF2guAQ0w5nl3AmLVn0r2lP9AFMxzPRnFAYlhIW++rbeXesP4VdV4hYaSX1zRWHngji0XxKNYWldj0I/q3b4klAgpYKL2cmYFjFT//bAWr7RAkBUQ8FRd94W0HyFZkvjws0Y8U0Ne06ULpVqK3q7feloyFeIV3jEJ78WQ0r2WnBKtcx9dFuW3BnmXX8rTMa4x6tbX+LAdoR3/QKVXkBBCgS9bZ1GIS0+nHxTGBXETDL8eSRGjwmPfvDuqN0w9lGPNuQ44n6dVYQHDwynY8C1dNZaDmLYlCRoAV0e+Np6SHNs6dW6CwXmnEYcSNA5lduL61x715HbhcyNAAEMAwr6k/3AJsod8dE14HpGTLgYSiJQFRyLNHYBBX/EE8NHztsSzN2CQOrZKF0=
  app: devops-brunoistvan
  on:
    repo: BrunoIstvan/DevOpsLab-HelloWorld
  skip_cleanup: 'false'
