language: python
python:
- 3.6.3
sudo: required
install:
- pip install flask
script:
- python test.py
deploy:
  provider: heroku
  api_key:
    secure: WBTgDj37vPCzs+vf0v9BPIsHBJrYtd3hVFzgQLmkW76emE18ynBlWH5/C0G6KukavOAKEdE/dlaEgaI5610YB8v+5B00Jlp8WJe37IZbSVhsSPcTMk1BGT1OnsHW9u5Sbi1z+/iZCLtFDvpgFLbgqqcjWNnQv75fXyyVm0B8jnEaOds0CwCEm3Qj3qMe1XkzvrGCv9FJT7AG/Wy4jpmz1gJK5pUVp7PS9fwRXQ3YpmrHfdNy7JSDme3F5zQBOCYC0IaxXX2cR5EaIOe5mdZG5TpXK/DzcnnogCjqqEIQfnG/Xm0Hkp39Po6PvKCk+gpibvk0c3OPA/IujNb+FF7ymG5qIyaq9e7Y/CRIk1T1bHzRa19jTaOs+7r/nj+wqI+x0DK2ILK10eaDIuPn4n1eEuL8Fenm05gNhczd17WS6gh1yDsqrqbuSF+8v5pdGfcBY2gC88hUBjobpG4YgYAybNnbiEBCLyA8uUYYnQra/xGrOJoattCJ9wQ7hyohlQyVMCYxJzS10Wl6B9gV59ZjiRr9WnCOwi/bkAfGbaEVQqdh6Z4QeqgUjt+Nf5OCJYP+1g0JbzO9mO7QShbEXUpw8Qasna/1EimlqXk9rMP16HjbFnXGlAcr9Ng7JnOq2ANIj2YJORrTtwCB384DL3vF0+3Le+7MopqHzk578avHyEw=
  app: devops-brunoistvan
  on:
    repo: BrunoIstvan/DevOpsLab-HelloWorld
  skip_cleanup: 'false'
