language: python
python:
- 3.6.3
sudo: required
install:
- pip install flask
script:
- python test.py

deploy:
  provider: heroku
  api_key:
    secure: $HEROKU_API_KEY
  app: devops-brunoistvan
  on:
    repo: BrunoIstvan/DevOpsLab-HelloWorld
  skip_cleanup: 'true'
